[build]
  ignore = "git diff --quiet $COMMIT_REF $CACHED_COMMIT_REF -- /"

[[redirects]]
  from = "/en/migration/0.21.0"
  to = "/en/migrate"
  status = 301

[[redirects]]
  from = "/en/core-concepts/component-hydration"
  to = "/en/core-concepts/partial-hydration"
  status = 301
